name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm install
      - run: npm install -g roblox-ts@1.1.1
      - uses: JS-DevTools/npm-publish@v1
        with:
            token: ${{ secrets.NPM_TOKEN }}
